CONFIG_NORDIC_QSPI_NOR=y
# STEP 4.1 - Increase number of sectors
# This is 512 for the nRF54L15 but can be smaller for other chips
CONFIG_BOOT_MAX_IMG_SECTORS=512

# Signature verification settings
CONFIG_BOOT_SIGNATURE_TYPE_RSA_LEN=3072
# Recommended for Security Level 4 environments
CONFIG_BOOT_VALIDATE_SLOT0=y
