CONFIG_AUDIO=y
CONFIG_AUDIO_DMIC=y         # for nRF SoCs
CONFIG_MFCC_SAMPLE_COUNT=320
CONFIG_CHANNELS_PER_SAMPLE=1
CONFIG_SAMPLING_RATE=16000
CONFIG_SYNC_MODE=1
CONFIG_MFCC_METHOD=1
CONFIG_BATCH_SIZE=4
