#SB_CONFIG_PARTITION_MANAGER=y
# Enable MCUboot
SB_CONFIG_BOOTLOADER_MCUBOOT=y
SB_CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=y
# Signature verification settings
SB_CONFIG_BOOT_SIGNATURE_TYPE_RSA=y
# Path to the key (Sysbuild looks relative to project root)
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${APP_DIR}/../.env/signing_key.pem"