# Enable floating point format specifiers
CONFIG_CBPRINTF_FP_SUPPORT=y
# Enables or disables the dedicated IMU processing thread.
CONFIG_IMU_ENABLE_THREAD=y

# Enable IMU interrupt-based FIFO handling
CONFIG_IMU_USE_INTERRUPT=y
# FIFO watermark level 
CONFIG_IMU_FIFO_WATERMARK=8
# Accelerometer ODR: 208 Hz
CONFIG_IMU_ACC_ODR=5
# Accelerometer FS: ±8g
CONFIG_IMU_ACC_FS=3
# Gyroscope ODR: 208 Hz
CONFIG_IMU_GYRO_ODR=5
# Gyroscope FS: ±500 dps
CONFIG_IMU_GYRO_FS=1
# FIFO batch rates (FIFO ODR must be less than or equal to the corresponding sensor ODR)
CONFIG_IMU_FIFO_ACC_ODR=5
CONFIG_IMU_FIFO_GYRO_ODR=5