name: HIL_Test

on:
  pull_request:
    branches: [ main ]

jobs:
  hardware-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Generate Signing Key
        run: |
          chmod +x scripts/run.sh
          ./scripts/run.sh -d --key
        
      - name: Build and Flash
        run: |
          chmod +x scripts/run.sh
          ./scripts/run.sh -d -b -f --app demo_apps

      - name: Run CLI Test
        run: |
          ./scripts/run.sh -d -t